USERNAME='aqim'
DBCONN='1'
MERCHANT_ID='30303003'
SECRET_KEY='SDFS4534534'
SQLALCHEMY_DATABASE_URI="mysql+mysqlconnector://root:@localhost/test"
SQLALCHEMY_TRACK_MODIFICATIONS='False'
FILE_UPLOAD='uploads/'
